### ISSUE TITLE
README.md 点击'点击体验' 提示'无法访问该文件'

### ISSUE THREAD

**Issue by GreenMashimaro** [vikadata/widget-summary#6]
# Problem Description：
## 点击README.md `立即体验`
![image](https://user-images.githubusercontent.com/23225539/185855048-b411fafc-67d5-4dae-8335-77441a54bcae.png)

## 跳转链接如下显示：
![image](https://user-images.githubusercontent.com/23225539/185855102-1d56e2dd-16a3-489a-8c89-e53a41dce554.png)

**Comment by Niko030303** [comment]
你好，已经重新替换链接，可以点击跳转了，跳转链接是：https://vika.cn/template/tpc000/tplkMfWM5CJnC/dsbrpXZLEt2ulksqqC

**Comment by GreenMashimaro** [comment]
thanks, very efficient update link.
